# Generated by Django 3.1.4 on 2020-12-27 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('reason', models.CharField(default='', max_length=140)),
                ('time_banned', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannedEmailDomain',
            fields=[
                ('reason', models.CharField(default='', max_length=140)),
                ('time_banned', models.DateTimeField(auto_now_add=True)),
                ('domain', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('reason', models.CharField(default='', max_length=140)),
                ('time_banned', models.DateTimeField(auto_now_add=True)),
                ('ip_addr', models.GenericIPAddressField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'banned IP',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP address')),
                ('notify_author', models.BooleanField(default=False)),
                ('time_authored', models.DateTimeField(auto_now_add=True)),
                ('mod_approved', models.BooleanField(default=True)),
                ('removed', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('author_website', models.URLField(blank=True, max_length=64, null=True)),
                ('author_email', models.EmailField(max_length=64)),
                ('author_name', models.CharField(blank=True, max_length=32, null=True)),
                ('content_md', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('content_html', models.TextField(blank=True, default='')),
                ('reply_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reason', models.CharField(max_length=140)),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP address')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
            ],
        ),
    ]
