# Generated by Django 3.1.4 on 2020-12-24 08:51

import comments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.URLField()),
                ('author_email', models.EmailField(max_length=254, null=True)),
                ('author_website', models.URLField(null=True)),
                ('author_twitter', models.CharField(max_length=50, null=True)),
                ('author_name', models.CharField(max_length=32, null=True)),
                ('content_md', models.CharField(default='', max_length=1000)),
                ('reply_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment', validators=[comments.models.validate_max_parents])),
            ],
        ),
    ]
