# Generated by Django 3.1.4 on 2020-12-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20201224_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
