# Generated by Django 3.1.4 on 2020-12-24 21:43

import comments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_md',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment', validators=[comments.models.validate_max_parents]),
        ),
    ]
