# Generated by Django 3.1.4 on 2020-12-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_authored_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notify_author',
            field=models.BooleanField(default=False),
        ),
    ]
