# Generated by Django 3.1.4 on 2020-12-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_notify_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
