# Generated by Django 3.1.4 on 2020-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20201224_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannedemail',
            name='id',
        ),
        migrations.AlterField(
            model_name='bannedemail',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
