# Generated by Django 3.1.4 on 2020-12-24 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_report_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_md',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip_addr',
            field=models.GenericIPAddressField(verbose_name='IP address'),
        ),
    ]
