# Generated by Django 3.1.4 on 2020-12-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20201224_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedip',
            options={'verbose_name': 'Banned IP'},
        ),
    ]
