# Generated by Django 3.1.4 on 2020-12-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_auto_20201224_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmailDomain',
            fields=[
                ('reason', models.CharField(default='', max_length=140)),
                ('time_banned', models.DateTimeField(auto_now_add=True)),
                ('domain', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bannedemail',
            name='reason',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='bannedip',
            name='reason',
            field=models.CharField(default='', max_length=140),
        ),
    ]
