# Generated by Django 3.1.4 on 2020-12-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20201224_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
        migrations.AddField(
            model_name='comment',
            name='mod_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
