# Generated by Django 3.1.4 on 2020-12-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_auto_20201225_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_website',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
    ]
