# Generated by Django 3.1.4 on 2020-12-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_auto_20201225_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ip_addr',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
    ]
