# Generated by Django 3.2.4 on 2021-07-11 18:32

import blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='text/plain', max_length=127)),
                ('body', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SY', 'Syndicated'), ('SC', 'Scheduled'), ('ER', 'Error')], default='SC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SyndicationTarget',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_warning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('content_type', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'unique_together': {('uuid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('slug_name', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='blog.content')),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('slug_name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateTimeField(blank=True, default=blog.models.utc_now)),
                ('published_date', models.DateTimeField(blank=True, default=blog.models.utc_now, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=blog.models.utc_now)),
                ('ordinal', models.IntegerField(default=blog.models.default_entry_ordinal)),
                ('reply_to', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('location', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(['mailto'])])),
                ('repost_of', models.URLField(blank=True, null=True)),
                ('content', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.content')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
            options={
                'unique_together': {('date', 'ordinal')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('url', models.URLField()),
                ('content_type', models.CharField(max_length=128)),
                ('caption', models.TextField(blank=True, null=True)),
                ('spoiler', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Syndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SY', 'Syndicated'), ('SC', 'Scheduled'), ('ER', 'Error')], default='SC', max_length=2)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndications', to='blog.entry')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='syndications', to='blog.syndicationtarget')),
            ],
            options={
                'unique_together': {('entry', 'target')},
            },
        ),
    ]
