# Generated by Django 3.2.4 on 2021-06-18 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyndicationTarget',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='syndication',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.syndicationtarget'),
        ),
    ]
