# Generated by Django 3.2.4 on 2021-06-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='syndications',
            field=models.ManyToManyField(through='blog.Syndication', to='blog.SyndicationTarget'),
        ),
    ]
