# Generated by Django 3.2.4 on 2021-06-17 20:31

import blog.models
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='summary',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ordinal',
            field=models.IntegerField(default=blog.models.default_entry_ordinal),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reply_to',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='repost_of',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='short_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='background_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
