# Generated by Django 3.2.4 on 2021-06-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_syndications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='syndications',
        ),
        migrations.AlterField(
            model_name='syndication',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndications', to='blog.entry'),
        ),
        migrations.AlterField(
            model_name='syndication',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='syndications', to='blog.syndicationtarget'),
        ),
    ]
