# Generated by Django 3.2.4 on 2021-07-02 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210702_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(['mailto'])]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reply_to',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
