# Generated by Django 3.2.4 on 2021-07-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210702_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='text/markdown', max_length=127)),
                ('content', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='content_html',
        ),
        migrations.AddField(
            model_name='tag',
            name='content_warning',
            field=models.BooleanField(default=False),
        ),
    ]
