# Generated by Django 3.1.4 on 2020-12-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleIdentity',
            new_name='GoogleToken',
        ),
    ]
