# Generated by Django 3.1.4 on 2020-12-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletoken',
            name='user',
        ),
    ]
