# Generated by Django 3.1.4 on 2020-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_googletoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubidentity',
            name='time_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='googleidentity',
            name='time_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='time_expires',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='time_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indiewebidentity',
            name='time_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
