# Generated by Django 3.1.4 on 2020-12-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201219_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubidentity',
            old_name='registered',
            new_name='time_registered',
        ),
        migrations.RenameField(
            model_name='googletoken',
            old_name='registered',
            new_name='time_registered',
        ),
        migrations.RenameField(
            model_name='indiewebidentity',
            old_name='registered',
            new_name='time_registered',
        ),
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('time_registered', models.DateField(auto_now_add=True)),
                ('google_id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.googletoken')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
