# Generated by Django 3.1.4 on 2020-12-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201219_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthAttempt',
            fields=[
                ('state', models.TextField(primary_key=True, serialize=False)),
                ('time_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
