# Generated by Django 3.1.4 on 2021-02-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('printer3d', '0001_initial'), ('printer3d', '0002_auto_20210201_0427')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('progress', models.FloatField(blank=True, default=0.0)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('send_enabled', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
