# Generated by Django 3.1.4 on 2021-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('progress', models.FloatField(blank=True, default=0.0)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('send_enabled', models.BooleanField(default=False)),
                ('image_timestamp', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
