# Generated by Django 3.1.4 on 2021-01-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NamedTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=8)),
                ('display_name', models.CharField(blank=True, max_length=32, null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.resource')),
            ],
            options={
                'unique_together': {('file', 'track_id')},
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(blank=True, max_length=8, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('x_forwarded_for', models.CharField(max_length=128, null=True)),
                ('remote_addr', models.GenericIPAddressField(null=True)),
                ('remote_host', models.CharField(max_length=64, null=True)),
                ('host', models.CharField(max_length=64, null=True)),
                ('referer', models.CharField(max_length=64, null=True)),
                ('language', models.CharField(max_length=32, null=True)),
                ('user_agent', models.CharField(max_length=64, null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.resource')),
            ],
            options={
                'index_together': {('file', 'track_id')},
            },
        ),
    ]
