# Generated by Django 3.1.4 on 2021-01-05 20:42

import analytics.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='host',
            field=analytics.models.TruncatingCharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='language',
            field=analytics.models.TruncatingCharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='referer',
            field=analytics.models.TruncatingCharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='remote_host',
            field=analytics.models.TruncatingCharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='track_id',
            field=analytics.models.TruncatingCharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='user_agent',
            field=analytics.models.TruncatingCharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='x_forwarded_for',
            field=analytics.models.TruncatingCharField(max_length=128, null=True),
        ),
    ]
