# Generated by Django 3.2.4 on 2021-06-20 18:41

from django.db import migrations, models
import indieauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.CharField(default=indieauth.models.generate_consent_request_id, max_length=16, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=128, unique=True)),
                ('me', models.CharField(max_length=128, unique=True)),
                ('redirect_uri', models.URLField()),
                ('response_type', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(max_length=512)),
                ('auth_code', models.CharField(default='', max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
