# Generated by Django 3.2.4 on 2021-06-20 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('indieauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrequest',
            name='client_id',
            field=models.URLField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('client_id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
    ]
