# Generated by Django 3.2.4 on 2021-06-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0002_auto_20210620_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsite',
            old_name='key',
            new_name='application',
        ),
    ]
