# Generated by Django 3.1.4 on 2020-12-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_oauthidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthidentity',
            name='provider',
            field=models.IntegerField(choices=[(0, 'google.com'), (1, 'github.com')]),
        ),
    ]
