# Generated by Django 3.1.4 on 2020-12-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201209_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthidentity',
            old_name='provider',
            new_name='provider_code',
        ),
    ]
