name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
          path: content

      - name: Import private key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{secrets.PRIVATE_KEY}}

      - name: Set Git credentials
        run: git config --global user.email "astrid@astrid.tech" && git config --global user.name "Astrid A. Yu"

      - name: Run build script
        run: content/build.sh content out

      - name: Publish
        run: content/publish.sh out
